name: Build and Release USP

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore OTAPI.UnifiedServerProcess/src/OTAPI.UnifiedServerProcess/OTAPI.UnifiedServerProcess.csproj

    - name: Build project
      run: dotnet build OTAPI.UnifiedServerProcess/src/OTAPI.UnifiedServerProcess/OTAPI.UnifiedServerProcess.csproj --configuration Release

    - name: Run compiled EXE
      run: |
        cd OTAPI.UnifiedServerProcess/src/OTAPI.UnifiedServerProcess/bin/Release/net9.0
        .\OTAPI.UnifiedServerProcess.exe

    - name: Upload output directory as Release asset
      uses: softprops/action-gh-release@v2
      with:
        files: OTAPI.UnifiedServerProcess/src/OTAPI.UnifiedServerProcess/bin/Release/net9.0/output/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
